ADB = 'adb-fastboot'
PARTITION = 'partition'
PAT = 'copy-partitions-20220613-signed.zip'
GAPPS = 'NikGapps-stock-arm64-15-20241104-signed.zip'
MAGISK = 'Magisk-v28.0.apk'
REPO_MAGISK = 'https://api.github.com/repos/topjohnwu/Magisk/releases/latest'
TWRPURL = 'https://dl.twrp.me/lake/twrp-3.7.0_9-0-lake.img'
TWRP = 'twrp-3.7.0_9-0-lake.img'